name: This a workflow title 
on: [push]

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO_NAME: ${{secrets.REPO_NAME}}

jobs:
  push-image-to-docker-hub:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: docker login
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
      
    - name: Get current date
      id: date
      run: echo $(date +'%Y-%m-%d--%H-%M-%S') >> date.txt
      
    - name: Read date from file
      id: read_date
      run: echo "::set-output name=date::$(cat date.txt)"
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $DOCKER_USER/$REPO_NAME:${{ steps.read_date.outputs.date }}
      
    - name: Docker Push
      run: docker push $DOCKER_USER/$REPO_NAME:${{ steps.read_date.outputs.date }}
