name: ci

#on:
#  push:
#    branches:
#      - 'main'

on:
  push:
    branches:
      - 'main'
    paths:
      - 'src/*' # İzlemek istediğiniz dizinin yolu

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Bump version and build
        run: |
          docker build -t razumuhin/py:${{github.run_number}} src
          docker push razumuhin/py:${{github.run_number}} 

      - name: Install yq
        run: sudo apt-get install python3-pip && sudo pip3 install yq 

      - name: Edit values.yaml
        run: |
          yq eval '.tag = "${{github.run_number}}"' mychart/values.yaml > mychart/temp.yaml && mv mychart/temp.yaml mychart/values.yaml
          # This line updates the 'tag' key in the values.yaml with the build number

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add mychart/values.yaml
          git commit -m "Update values.yaml"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} 
         