name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - 
        name: Make script executable
        run: chmod +x bump_version.sh

      -
        name: Bump version and build
        run: |
          new_version=$(./bump_version.sh)
          echo "New version: $new_version"
          docker build -t razumuhin/py:$new_version .
          docker push razumuhin/py:$new_version

